title: A personal blog
description: Footprints on the sands of time
url: http://localhost:4000# site urls
avatar: # path/to/avatar for index page. e.g. /assets/img/avatar.jpg
favicon: # path/to/favicon for site. e.g. /assets/img/favicon.ico
google_analytics: # google analytics id
disqus_shortname: # disqus_shortname for disqus comment system

# Content for about page.
# Each paragraph will be a <p> tag which is inserted to about
# page. text_align is used to align the text. Default is left.
# Other two values are center and right. If there are some links
# in your paragraph, use '?link?' to take the place of a link.
# And then write the real link under links. name is the link
# text. url is the link. when external is set as true, then
# a new whidow will be open when link is clicked.
#
about:
  - paragraph: Hi ! I am Anurag, currently in my senior year of undergraduate degree. I am interested in Maths, Programming and Literature. This little blog is mostly for personal use and is meant to keep track of my thoughts and writings. If you find something interesting please drop a line.
    text_align: center

#  - paragraph: This was built using the Jekyll theme ?link? built by ?link? and modified by me.
#    text_align: center
#    links:
#      - name: Book
#        url: https://github.com/kkninjae/book
#        external: true
#      - name: Lang Liu
#        url: http://kkninjae.com/about/
#        external: false
    
